### ISSUE TITLE
Added support for Debian-12 (bookworm)

### ISSUE THREAD

**Issue by easpeagle** [outsideopen/ansible-role-bigfix-client#22]
Looks like we're missing support for Debian-12. Could you add that, please?

**Comment by dlundgren** [comment]
Since Debian 12 is not "officially" supported in the BigFix downloads this would require some form of mapping in the `generate.py` script. 

At the moment, a better solution would be to allow users to specify a way to override what the variable file is being used.

Toward that end I made it more useful on the lookup to be able to set, which will also allow to map other detected OS's as well.
```yaml
bigfix_client_override_vars:
  Debian-12-x86_64: Debian-11-x86_64
```

**Comment by dlundgren** [comment]
While not explicitly mapped in the 2.0.6 release, the ability to create a mapping for the OS via the `bigfix_client_override_vars` variable mentioned above does work.
